switch travel time to arrival time of a player, update test
MANVSim/MANVSim pull request #206
Opened 2024-07-31 13:57 UTC by YIllmann

see title.

@n00on @lukas0820 I changed the attribute in the api.yml as well as the describtion.

2024-07-31 14:17 UTC, n00on commented
@YIllmann did you maybe forget to checko in the api.yml? I don't see it in the diff

2024-07-31 20:25 UTC, YIllmann commented
> @YIllmann did you maybe forget to checko in the api.yml? I don't see it in the diff

that may be correct :D. Update ist pushed

2024-08-04 12:35 UTC, lukas0820 commented
@YIllmann there is a naming conflict between api.yaml and lobby.py. In api.yaml, the parameter is named scenario_start_time, while in lobby.py, it is referred to as starting_time.

I assume that starting_time might be the correct one

2024-08-04 12:38 UTC, lukas0820 commented
I`ve noticed that the starting time is in milliseconds and the arrival time in seconds in api.yaml. Is this correct or should it both be seconds?

2024-08-04 19:27 UTC, simohlsen requested changes

2024-08-04 19:27 UTC, simohlsen commented on server/execution/entities/player.py
> +        self.alerted_timestamp = 0
Would set it to `-1`

2024-08-04 19:27 UTC, simohlsen commented on server/execution/entities/player.py
> +            self.alerted_timestamp = 0
Would set it to `-1`

2024-08-05 09:36 UTC, YIllmann commented
> I`ve noticed that the starting time is in milliseconds and the arrival time in seconds in api.yaml. Is this correct or should it both be seconds?

both should seconds.

2024-08-05 10:30 UTC, simohlsen approved these changes

2024-08-05 12:55 UTC, merged