Feature/server/227 server define and implement user roles
MANVSim/MANVSim pull request #232
Opened 2024-08-15 13:59 UTC by simohlsen

Closes #227

2024-08-16 13:09 UTC, YIllmann approved these changes

2024-08-16 13:09 UTC, YIllmann commented on server/dbsetup.py
> +    #insert(Execution(id=23456, name="Kreativer Name", scenario_id=1))  # FIXME: broken scenario
delete. useless anyway

2024-08-16 22:31 UTC, H1ghBre4k3r approved these changes
LGTM

2024-08-17 14:31 UTC, 7erra requested changes

2024-08-17 14:31 UTC, 7erra commented on server/utils/decorator.py
>  def admin_only(func: Callable):
This function now seems like a repetition of `role_required`. IMO this should be removed.

2024-08-17 14:31 UTC, 7erra commented on server/scenario/web_api/scenario.py
> -@admin_only
Why not protect all endpoints even if they are "only" GET requests? Sensitive data might get leaked.

2024-08-18 06:18 UTC, 7erra approved these changes

2024-08-18 12:28 UTC, merged