Server: Endpoint for Performed Actions
MANVSim/MANVSim pull request #342
Opened 2024-09-15 11:46 UTC by simohlsen

Closes #338

2024-09-15 11:51 UTC, YIllmann approved these changes
lgtm if the typechecker is resolved :P

2024-09-15 12:31 UTC, lukas0820 requested changes
This is not exactly what we need; we can already access the performed actions via the patient endpoint. What’s missing are the conditions. It would be great if we could call the `/run/action/perform/result` endpoint multiple times.

2024-09-15 14:09 UTC, YIllmann commented
> This is not exactly what we need; we can already access the performed actions via the patient endpoint. What’s missing are the conditions. It would be great if we could call the `/run/action/perform/result` endpoint multiple times.

The perform/result endpoint won’t be modified for multiple request. That would invalid the action logic. However we can extend the performedAction entity by the conditions that are returned as a result. Then you can use the history endpoint from this pr to resolve the conditions for predecessor actions.

2024-09-15 15:13 UTC, lukas0820 commented
> > This is not exactly what we need; we can already access the performed actions via the patient endpoint. What’s missing are the conditions. It would be great if we could call the `/run/action/perform/result` endpoint multiple times.
> 
> The perform/result endpoint won’t be modified for multiple request. That would invalid the action logic. However we can extend the performedAction entity by the conditions that are returned as a result. Then you can use the history endpoint from this pr to resolve the conditions for predecessor actions.

I dont like the idea of a separate performed action endpoint because we already have this information in the PatientDTO type and can access it with `/patient/arrive`

I would prefer one of the following two options:

- Add a property `conditions` of type `ConditionDTO` to `PerformedActionDTO`  and make sure to add it everywhere the `PerformedActionDTO` type is used. In this case `/run/action/perform/result` does not need the conditions as a separate parameter in the response as it is already contained in the patient object.
- Add a separate endpoint /patient/{performedActionId}/conditions which returns the conditions only for a single performedAction id

2024-09-16 11:26 UTC, simohlsen commented
I added the resulting conditions of an action to the performed action object. So you don't need a separate endpoint then or what else should I change? @lukas0820

2024-09-18 23:44 UTC, lukas0820 commented on server/execution/api/action.py
> +            "conditions": patient_conditions
Are these conditions redundant here? Since we're already returning the Patient object that contains the performed actions with the conditions

2024-09-19 08:30 UTC, lukas0820 requested changes
resulting conditions in patients performed action seems to be always null (tested with `patient/arrive`)

```
        "performed_actions": [
            {
                "action": {
                    "duration_sec": 10,
                    "id": 0,
                    "media_references": [
                        {
                            "media_reference": "media/static/image/no_image.png",
                            "media_type": "IMAGE",
                            "text": null,
                            "title": null
                        }
                    ],
                    "name": "Patient händisch untersuchen",
                    "required_role": 100,
                    "resources_needed": [],
                    "results": [
                        "Verletzung",
                        "Haut",
                        "Abdomen",
                        "Rekapzeit"
                    ]
                },
                "execution_id": 1,
                "id": "3b3375e2-14e8-436d-b82a-4934a3278e3c",
                "player_tan": "123ABC",
                "resources_used": [],
                "resulting_conditions": null,
                "time": 1726732978
            },
```

2024-09-19 17:41 UTC, simohlsen commented
> resulting conditions in patients performed action seems to be always null (tested with `patient/arrive`)

Sorry, my bad, there was a typo in the attribute reference. It should work now.

2024-09-19 20:26 UTC, lukas0820 approved these changes

2024-09-19 20:26 UTC, merged